### ISSUE TITLE
Truncate Authie::Session#user_agent before it's persisted: "Data too long for column 'user_agent'"

### ISSUE THREAD

**Issue by admpsktt** [adamcooke/authie#11]
Hi @adamcooke. I think https://github.com/adamcooke/authie/commit/d315875 is incomplete. I use version 1.2.4 of this gem on a project at work (thanks so much for your work on this) and required this fix after hitting the same issue that you undoubtedly did but I'm not quite ready to upgrade to the next major version.

The `before_create` above, where it assigns `AuthieSession#user_agent` in a controller context is still able to throw the same error.

Locally, I've implemented a fix for this by overriding `AuthieSession#user_agent=` like so:

``` 
module Authie
  class Session < ActiveRecord::Base

    def user_agent=(value)
      super value[0,255]
    rescue
      super
    end

  end
end
```

This seems to take care of the issue and allows me to save `Authie::Session` instances again.

I couldn't override the `before_create` as it's implemented with an anonymous block and wasn't sure I could guarantee the callback order if I'd added another `before_create`. `before_create` is the last callback in the stack before a record is persisted so I couldn't add another (different) one.

Just wanted to bring this to your attention. Hope this is helpful.

**Comment by adamcooke** [comment]
The `before_validation` will always be run before the `before_create` so I'm puzzled why you're seeing any errors here. Do you have some examples of the exact error you're receiving?

Thanks!

**Comment by admpsktt** [comment]
Hi @adamcooke. Thanks for getting back. I was able to reproduce the error mentioned in the title of the issue by faking a user-agent of 256 characters or more in Chrome developer tools and logging in to my app through an `Authie::Session`.

`before_validation` is indeed run before `before_create` but in `before_create`, when in a controller context, `self.user_agent=` is invoked again, overriding what happens in the `before_validation` callback.

If you are able to reproduce the problem, I suspect it can be resolved by changing the line in the `before_create` from:

`self.user_agent = controller.request.user_agent`

to:

`self.user_agent = controller.request.user_agent[0,255] if controller.request.user_agent.is_a? String`

Am I missing something?
