### ISSUE TITLE
Upgrade from version 2 to 3 instructions

### ISSUE THREAD

**Issue by emmanuelmillionaer** [adamcooke/authie#13]
Hi @adamcooke , thanks for this great gem! 🙂 💯 

In an existing project I would like to upgrade from authie version 2 to 3.

Can you provide some advices/instructions on how to do so?
The errors I get have to do with `undefined method `token_hash=' `. Is the solution to simply add a migration?

Thanks for your efforts!

**Comment by adamcooke** [comment]
You should just need to re-run `rake authie:install:migrations` on the project and you should get the new migrations.

**Comment by emmanuelmillionaer** [comment]
Thanks @adamcooke seems to work! 👍
