### ISSUE TITLE
Toggle Authie in certain controllers

### ISSUE THREAD

**Issue by BatedUrGonnaDie** [adamcooke/authie#14]
We have some controllers for a public api that we would like to turn off authie for.  Is this possible to do this cleanly?  I tried doing a `skip_before_action` with `set_browser_id` and `touch_auth_session` but it still runs some of the code.  We would like to be able to disable it completely for all but 1 or 2 of the endpoints as they don't need any kind of session checking (some of the endpoints still rely on cookie authentication).

**Comment by adamcooke** [comment]
If you skip `set_browser_id` and `touch_auth_session` there isn't anything else it should be doing unless you're calling `current_user`, `logged_in?` or `auth_session`. Do you know what it's doing that you'd like to avoid?

**Comment by BatedUrGonnaDie** [comment]
Ah, it looks like `current_user` is called in those methods.  Didn't realize that would cause stuff to happen.  Thanks for the info, appreciated!
