### ISSUE TITLE
Rails 6 + Zeitwerk name error

### ISSUE THREAD

**Issue by BatedUrGonnaDie** [adamcooke/authie#17]
After upgrading to rails 6 and enabling the new autoloader, it seems rails is no longer able to find authie session properly throwing this error: `uninitialized constant Authie::Session (NameError)`.  The error is specifically being thrown because of this line `rescue_from Authie::Session::ValidityError, with: :auth_session_error`.  If I turn back on the classic autoloader then no errors are thrown.

Let me know if you need anymore info from me about this.

**Comment by fxn** [comment]
This line in the engine code does not seem to be correct:

```ruby
config.autoload_paths += Dir["#{config.root}/lib/**/"]
```

You want `lib` to represent the root namespace. That is, you want `Authie` to belong to `Object`. It does not make sense to say that `lib/authie` represents also a root namespace.

Classic tolerated this as a side-effect of the implementation, but Zeitwerk is more strict and detects nested namespaces.

The configuration would be simply

```ruby
config.autoload_paths += Dir["#{config.root}/lib"]
```
