### ISSUE TITLE
v3.3.0 release?

### ISSUE THREAD

**Issue by mxlje** [adamcooke/authie#19]
[This commit](https://github.com/adamcooke/authie/commit/d27ea7849031a985cb25bc053f7304fee6118a68#diff-214ea28dbe3b4b2f6fb99b25775cf1b9), which changed auto-loading behaviour, bumped the version to `3.3.0` but that hasn’t been released to RubyGems yet (the latest is `3.2.0`).

I assume that that change also closes #17, as it completely removes the line in question. That would be great because I could install authie regularly instead of pointing to master when upgrading to Rails 6.

So:

1. Release `3.3.0` to RubyGems
2. Close #17 (?)

Thank you!

**Comment by adamcooke** [comment]
Done :) Resolves #17

**Comment by mxlje** [comment]
Thank you Adam 🙏🏼
